"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

paths = dict()
with open('urls.txt') as fp:
	for item in fp:
		temp = item.split('=')
		paths[temp[0]] = temp[1].strip('\n')


APP = ['run.py']
DATA_FILES = ['urls.txt']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)